### ISSUE TITLE
More column settings in Stocks > Stock Lists

### ISSUE THREAD

**Issue by Carbide3600** [stocknear/frontend#14]
Inside the lists under the Stocks > Stock Lists, it would be awesome to

- 1) either have some more important metrics for each stock like P/E ratio, the % change in stock price (over the last day, month, year) as individual columns (important for -ii) or even better - being able to freely configure the columns, similarly to the possibility of choosing columns from a criteria list under Stock Screener

- 2) being able to sort the columns in these lists in ascending or descending order, just like in the lists under Stock Screener. This ability to sort in ascending / descending would also be nice for other lists like Top Shorted Stocks, ETF Providers, Dividends/Earnings calendar, Tracker Datasets etc...

**Comment by MuslemRahimi** [comment]
Sounds great, will add it

**Comment by MuslemRahimi** [comment]
Done
