### ISSUE TITLE
Split of the overview tab 

### ISSUE THREAD

**Issue by Traijan1** [stocknear/frontend#3]
First of all, I really like your site and I think it's great to have it.

However, one thing that struck me immediately was the overview tab. One of the first things I do is look for the forecasts for revenue, EPS, etc., and to be honest, I couldn't find them at first.

I think the forecasts could have their own tab. I also think the AI features could be in a separate tab.

**Comment by MuslemRahimi** [comment]
Sure will fix that

**Comment by Traijan1** [comment]
I reviewed the overview tab and have a few suggestions for how the information could be better organized:

"AI Analyst Insight": Analyst Category under "Analyst Rating" section.
"Predictive Fundamentals":  Stats -> Fundamental. It would be beneficial to include a percentage change metric here to enhance the growth analysis.
"Revenue Breakdown": Stats -> Fundamental.
"Enterprise Value": Stats -> Fundamental.
"Share Statistics": Stats -> Shares.
"Shareholder Breakdown": Stats -> Shares.
"Stock Splits": Stats -> Shares.
Additionally, I believe it would be more effective if the "Worst 10 Drawdowns" section were placed last in the Stats -> Fundamental category.

Also for the Options Tab:
- Swap Data
- Latest Options Activity
- Options Net Flow
- (maybe Borrowed Share)

Consider renaming "Stats" to "Fundamentals" and changing "Stats->Fundamental" to "Stats->Overview."

**Comment by MuslemRahimi** [comment]
Done!
