### ISSUE TITLE
Heatmap => cumulative return shows an impossible value

### ISSUE THREAD

**Issue by Traijan1** [stocknear/frontend#4]
"Today, Health Care took the lead as the S&P500 largest loser, marking a cumulative return of -104.58%"

![image](https://github.com/user-attachments/assets/af76a1b6-3a82-4481-9764-9f8d2bd9a91b)

**Comment by MuslemRahimi** [comment]
Thanks I fixed the issue now instead of cumulative return I now display the average return of each Sector.
